### ISSUE TITLE
Макет

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/FSD_task2#10]
1. Форму лучше привязать к футеру и хедеру, т.е. сдвинуть ближе к центру на широких экранах
2. Футер должен прижиматься к низу страницы, об этом, вроде, в бест практис есть.
https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#1.15
![image](https://user-images.githubusercontent.com/18898493/118468594-bba93180-b726-11eb-91d7-2fcc1f2c4340.png)

3. Пагинация, по мере листания круг превращается в прямоугольник со скругленными углами.
![image](https://user-images.githubusercontent.com/18898493/118471763-eb0d6d80-b729-11eb-876b-15d7a9ea530d.png)

4. Здесь наоборот при наведении на карточку должны затеняться стрелки
![image](https://user-images.githubusercontent.com/18898493/118472479-b3eb8c00-b72a-11eb-80f9-1f215835b1e5.png)
Вот так
![Peek 2021-05-17 16-14](https://user-images.githubusercontent.com/18898493/118472849-22c8e500-b72b-11eb-9610-155da70fdd33.gif)

5. Ссылки "Войти" и "Зарегистрироваться" в шапке должны вести на соответствующие страницы. На странице авторизации кнопка "Создать" должна вести на страницу регистрации. Лого в шапке надо сделать ссылкой на главную.

**Comment by Constantine-P** [comment]
6. Тут есть кнопка применить, поэтому пока ее не нажали, поле не должно меняться
![image](https://user-images.githubusercontent.com/18898493/121769273-6ffe7200-cb84-11eb-87e0-1a4e18888ca6.png)

**Comment by Constantine-P** [comment]
7. Макет должен быть резиновым 320+, насколько я помню
![image](https://user-images.githubusercontent.com/18898493/121769371-19456800-cb85-11eb-84b4-31e535b6161f.png)

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/121769481-a5f02600-cb85-11eb-9cac-230d6d6fdf17.png)

**Comment by Constantine-P** [comment]
6. ![Peek 2021-06-15 10-59](https://user-images.githubusercontent.com/18898493/121995619-0d49e800-cdc9-11eb-9df8-ab322bcc8def.gif)
Еще, когда кликаю на стрелку, меню открывается, но обратно не закрывается

8. Ничего не происходит
![Peek 2021-06-15 11-06](https://user-images.githubusercontent.com/18898493/121996080-d4f6d980-cdc9-11eb-82d1-0098a91622b4.gif)

**Comment by Constantine-P** [comment]
8. ![image](https://user-images.githubusercontent.com/18898493/121996449-78e08500-cdca-11eb-9811-3a66e9843b8e.png)

**Comment by Constantine-P** [comment]
На gh pages не нашел изменений

**Comment by ArtemDmitrenko** [comment]
> На gh pages не нашел изменений

Обновил gh pages

**Comment by Constantine-P** [comment]
8. Не сделан
9. Нужен одинаковый отступ, некрасиво же
![image](https://user-images.githubusercontent.com/18898493/124905386-ccc83d80-e007-11eb-8cd5-95503ea083a5.png)
10. Меню лучше на весь экран и шрифт побольше
![image](https://user-images.githubusercontent.com/18898493/124905618-08fb9e00-e008-11eb-94f5-4f61c672d2f9.png)
