### ISSUE TITLE
Дублирование css свойств, неверное значение

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/FSD_task2#20]
![image](https://user-images.githubusercontent.com/18898493/118608226-451a3b80-b7db-11eb-84d4-354e5431cf59.png)

**Comment by Constantine-P** [comment]
Лучше делать одним свойством:
![image](https://user-images.githubusercontent.com/18898493/122000524-cb24a480-cdd0-11eb-984b-2dd74d21c09b.png)

**Comment by Constantine-P** [comment]
У color нет такого значения. Можешь линтер для стилей приделать, чтобы это фиксить
![image](https://user-images.githubusercontent.com/18898493/122000979-72094080-cdd1-11eb-9eb8-cf66038dede1.png)

**Comment by Constantine-P** [comment]
![image](https://user-images.githubusercontent.com/18898493/124955171-abcc1080-e038-11eb-9ad9-ea09218a4d12.png)
![image](https://user-images.githubusercontent.com/18898493/124955528-ee8de880-e038-11eb-8ca1-a6d072f174aa.png)
![image](https://user-images.githubusercontent.com/18898493/124955585-f8175080-e038-11eb-82d6-393e9303b6f1.png)
![image](https://user-images.githubusercontent.com/18898493/124955620-006f8b80-e039-11eb-9226-8ab9dc49fd86.png)
![image](https://user-images.githubusercontent.com/18898493/124955744-1d0bc380-e039-11eb-90c0-912118c5ab40.png)
![image](https://user-images.githubusercontent.com/18898493/124955809-30b72a00-e039-11eb-8caa-37b3d62a761c.png)
![image](https://user-images.githubusercontent.com/18898493/124955952-4f1d2580-e039-11eb-88bf-3bf63703fc53.png)
![image](https://user-images.githubusercontent.com/18898493/124955988-5a705100-e039-11eb-8b01-67515524f2ad.png)
![image](https://user-images.githubusercontent.com/18898493/124956071-6e1bb780-e039-11eb-9146-f2658c872cef.png)

**Comment by ArtemDmitrenko** [comment]
<img width="1440" alt="Снимок экрана 2021-07-11 в 19 48 49" src="https://user-images.githubusercontent.com/48836855/125203623-d4931680-e281-11eb-9286-799a825984a7.png">

@Constantine-P cорри за глупый вопрос: подключил rule в stylelint: [declaration-block-no-shorthand-property-overrides](https://stylelint.io/user-guide/rules/list/declaration-block-no-shorthand-property-overrides) , слева добавил padding и padding-left, но stylelint почему-то игнорирует это правило. При этом declaration-block-no-duplicate-properties работает корректно..

**Comment by ArtemDmitrenko** [comment]
@Constantine-P я правильно понимаю, что со шрифтами ошибка в том, что не указан запасной? В таком случае не понимаю какой запасной шрифт писать для Material Icons?

**Comment by Constantine-P** [comment]
Для Material Icons, конечно не нужен, не обратил внимание на название.
Со линтером это не ошибка, насколько я понимаю:
![image](https://user-images.githubusercontent.com/18898493/125395291-ce5d8100-e3cc-11eb-9fde-9cf30b881e4c.png)

**Comment by Constantine-P** [comment]
Так не надо разбивать имя, ухудшает читаемость
![image](https://user-images.githubusercontent.com/18898493/125951138-269342b2-f2d1-43a0-b70d-68f12b765aa3.png)

**Comment by ArtemDmitrenko** [comment]
Видимо, я подправил эту ошибку в одном из предыдущих коммитов. Сейчас все ок:
<img width="575" alt="Снимок экрана 2021-07-17 в 11 30 28" src="https://user-images.githubusercontent.com/48836855/126031276-c88af979-83c2-4538-8cec-037e3e1a98b9.png">
