### ISSUE TITLE
Харкод

### ISSUE THREAD

**Issue by Constantine-P** [ArtemDmitrenko/FSD_task2#22]
1. Здесь напрашиваются миксин c циклом
![image](https://user-images.githubusercontent.com/18898493/118628339-56207800-b7ee-11eb-88d2-9c58746f34d6.png)

Пункты меню лучше вынести в отдельный файл, и оттуда импортировать с помощью require

2. Здесь тоже лучше вынести и передавать как аргумент миксина "+nav-menu(menuItems)"
![image](https://user-images.githubusercontent.com/18898493/118629247-3b023800-b7ef-11eb-8cb3-d3332c75d5d6.png)

**Comment by ArtemDmitrenko** [comment]
Подскажи пож где можно почитать о том как импортировать в файл pug данные из отдельного файла с помощью require?

**Comment by Constantine-P** [comment]
https://www.google.com/search?q=pug+require+json
Должно работать:
const menuItems = require('путь/до/файла.js(или json)')
