### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#38]
Сокращение обычно используются только в случае необходимости. Тут на мой взгляд её нет) Имя от данных сокражений не сильно сократилось, но вот читаемость снизилась

![image](https://user-images.githubusercontent.com/43137324/145164817-49721c52-d7cc-4027-8117-f505d6a9a1a2.png)
![image](https://user-images.githubusercontent.com/43137324/145164967-29ebd86f-cd53-4813-a6bd-6a38eee91134.png)

Я не знаток английского, но в подобных конструкциях, например, confirmation вроде должнен быть в роли атрибутивного существительного и идти перед form. И отдельные слова должны отделяться тире

![image](https://user-images.githubusercontent.com/43137324/145165603-7cc9bcfc-40c5-41b4-96cd-ec8be85506c1.png)

**Comment by ArtemDmitrenko** [comment]
> Сокращение обычно используются только в случае необходимости. Тут на мой взгляд её нет) Имя от данных сокражений не сильно сократилось, но вот читаемость снизилась
> 
> ![image](https://user-images.githubusercontent.com/43137324/145164817-49721c52-d7cc-4027-8117-f505d6a9a1a2.png) ![image](https://user-images.githubusercontent.com/43137324/145164967-29ebd86f-cd53-4813-a6bd-6a38eee91134.png)
> 
> Я не знаток английского, но в подобных конструкциях, например, confirmation вроде должнен быть в роли атрибутивного существительного и идти перед form. И отдельные слова должны отделяться тире
> 
> ![image](https://user-images.githubusercontent.com/43137324/145165603-7cc9bcfc-40c5-41b4-96cd-ec8be85506c1.png)

Насчет form согласен абсолютно с тобой, что более правильно именовать как ты предлагаешь, поэтому поменяю конечно. Просто когда я делал руководствовался тем, что все формы идут одна за другой и сразу все видны в папке components

**Comment by Everrest1** [comment]
camelCase?)

![image](https://user-images.githubusercontent.com/43137324/146786167-0c4c7425-9e20-46b9-a91e-aab38fb2f89f.png)

**Comment by Everrest1** [comment]
Наверное, лучше указать что-то вроде opened, show всё-таки не используется как прилагательное

![image](https://user-images.githubusercontent.com/43137324/147271044-8d419d0d-bb7d-40bd-af33-8b88407f28d4.png)

**Comment by Everrest1** [comment]
Не думаю, что именование элементов цифрами уместно

![image](https://user-images.githubusercontent.com/43137324/147764749-2cb6d37f-ae6e-418d-b09b-815f6c6d8e67.png)

**Comment by ArtemDmitrenko** [comment]
fixed in this commit 4daea2fea92c1de7951fec4b88c6b9af910fde0f

**Comment by Everrest1** [comment]
Зачем геттер вместо обычного метода или поля? Зачем два указания на булево значение? Почему у дата атрибута buttons его нет?))

![image](https://user-images.githubusercontent.com/43137324/149358886-cfe47427-0da3-4a86-8084-e09ad5237522.png)

**Comment by Everrest1** [comment]
`is` здесь лишнее

![image](https://user-images.githubusercontent.com/43137324/149794935-36b45527-e969-4a48-8422-680d3f219716.png)

**Comment by Everrest1** [comment]
footer-big не совсем корректное имя с т.з. английского языка + странная логика получается, футер использует большой футер и дополняет его чем-то. Ну и лучше не делать несколько блоков для одного и того же элемента интерфейса, которые имеют несколько небольших отличий, состояние можно донастроить в параметрах

![image](https://user-images.githubusercontent.com/43137324/150818753-9975d0e4-073e-4636-816f-3fc07e05155c.png)

**Comment by Everrest1** [comment]
По имени массива должно быть понятно, что это массив, оно должно быть во множественном числе

![image](https://user-images.githubusercontent.com/43137324/151830162-88a0d77e-61cd-45ce-b848-7bb4a2d13b32.png)

**Comment by Everrest1** [comment]
Странное имя метода, который ничего не ищет и не возвращает

![image](https://user-images.githubusercontent.com/43137324/151830856-40043fd8-d4f8-4623-b38a-b2eb921ee9e1.png)

**Comment by Everrest1** [comment]
Дай пожалуйста более осмысленные имена)

![image](https://user-images.githubusercontent.com/43137324/152150036-6032126d-ae4a-48e2-ac5d-fdbc3a79f502.png)

**Comment by Everrest1** [comment]
Имя элемента надо поменять. Зачем стили передавать через атрибут style?)

![image](https://user-images.githubusercontent.com/43137324/152152134-8fddae3b-0c8e-438b-9cbb-312704020245.png)

**Comment by Everrest1** [comment]
Пропустил

> Дай пожалуйста более осмысленные имена)
> 
> ![image](https://user-images.githubusercontent.com/43137324/152150036-6032126d-ae4a-48e2-ac5d-fdbc3a79f502.png)

**Comment by Everrest1** [comment]
Наверное всё-таки не show, а set

![image](https://user-images.githubusercontent.com/43137324/152373363-1053138a-2ee3-42be-aeeb-1eacaf600b70.png)
