### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#39]
Тут код явно можно сократить

![image](https://user-images.githubusercontent.com/43137324/145165843-bbc4a456-052a-4c42-bcba-02313b4e4c44.png)

**Comment by Everrest1** [comment]
Тут тоже можно проще

![image](https://user-images.githubusercontent.com/43137324/146782821-6a1545cc-e94c-46ae-b706-786ba18b3aa3.png)

**Comment by Everrest1** [comment]
Тут тоже можно сделать проще

![image](https://user-images.githubusercontent.com/43137324/146786103-b34b44f9-d771-485a-ace3-74f91e60a2ff.png)

**Comment by Everrest1** [comment]
В одном файле не должно быть больше одного миксина

![image](https://user-images.githubusercontent.com/43137324/147270681-2399593c-e9ec-42f4-9066-0bcb22b196bf.png)

**Comment by ArtemDmitrenko** [comment]
> В одном файле не должно быть больше одного миксина
> 
> ![image](https://user-images.githubusercontent.com/43137324/147270681-2399593c-e9ec-42f4-9066-0bcb22b196bf.png)

Это где-то в BP прописано? а чем это вызвано поясни пож? я ведь просто миксин использую по сути как переменную. И если это критично, то я как лучше сделать - вынести listOfOptions в отдельную папку и инклюдить его сюда в checkbox-button?

**Comment by Everrest1** [comment]
Да, [4.4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.4). В данном проекте миксины используются для переиспользования блоков, вместо переменной их использовать не нужно, есть же обычная переменная) Выносить в отдельную папку можно, если сущность соответствует определению отдельного независимого блока

**Comment by ArtemDmitrenko** [comment]
> Да, [4.4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.4). В данном проекте миксины используются для переиспользования блоков, вместо переменной их использовать не нужно, есть же обычная переменная) Выносить в отдельную папку можно, если сущность соответствует определению отдельного независимого блока

А как в обычной переменной можно использовать pug-ий цикл each in? Прогуглил не нашел ничего похожего

**Comment by Everrest1** [comment]
Ага, вот так)

Для булевых переменных не нужно выполнять операции сравнения)
![image](https://user-images.githubusercontent.com/43137324/147762029-450a6089-2680-4d2c-b88a-c31bd93651e9.png)

Можно сделать ещё чуть проще) Если, например, добавлять модификатор "_expandable" только на корневой элемент .checkbox-button, то этого будет достаточно, чтобы применить стили ко всем остальным элементам блока используя вложенность scss
Вот у тебя пример даже есть, только вместо :checked модификатор

![image](https://user-images.githubusercontent.com/43137324/147762469-7342d4c7-b5ec-481c-a0fc-940bf332d369.png)

Тогда не нужно будет менять имена элементов и тернарников станет поменьше)

**Comment by Everrest1** [comment]
Не пойму какой из файлов проверять?)

![image](https://user-images.githubusercontent.com/43137324/148407709-603b9b61-3e07-45ba-97ad-5ed9bdeddbfd.png)

**Comment by ArtemDmitrenko** [comment]
> Не пойму какой из файлов проверять?)
> 
> ![image](https://user-images.githubusercontent.com/43137324/148407709-603b9b61-3e07-45ba-97ad-5ed9bdeddbfd.png)

Удалил лишний

**Comment by Everrest1** [comment]
Булевы переменные дожны именоваться в соответствии с [п.2.4](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#2.4)

По названию блока должно быть понятно чем блок является checkbox-button - говорит о том, что это кнопка с чекбоксом, но это не так, блок представляет собой список из чекбоксов

forLabel не используется

![image](https://user-images.githubusercontent.com/43137324/148964161-3e7561d8-1c3a-45dd-847f-851edf8c4f8f.png)

Сокращения лучше не использовать

![image](https://user-images.githubusercontent.com/43137324/148965009-7a1b1334-2aec-4bfa-a72f-a1ce1a6b4d68.png)

isExpanded говорит скорее о состоянии открыт/закрыт
Я бы делал проверку на тип блока перед тем, как вешать обработчики

![image](https://user-images.githubusercontent.com/43137324/148965408-b2d99d38-b288-4bd0-8df2-17a3faa43a94.png)
