### ISSUE TITLE
Иконки

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#40]
А зачем?) Почти всегда иконки можно загрузить из макета или использовать готовые наборы, например, Material Icons. Переиспользовать что-то уже готовое - хорошая практика)

![image](https://user-images.githubusercontent.com/43137324/146784681-9da768ad-73c0-47d7-be1b-b90f975fde55.png)
![image](https://user-images.githubusercontent.com/43137324/146784768-629e72de-387f-491f-b343-35fad882b787.png)

**Comment by ArtemDmitrenko** [comment]
> А зачем?) Почти всегда иконки можно загрузить из макета или использовать готовые наборы, например, Material Icons. Переиспользовать что-то уже готовое - хорошая практика)
> 
> ![image](https://user-images.githubusercontent.com/43137324/146784681-9da768ad-73c0-47d7-be1b-b90f975fde55.png) ![image](https://user-images.githubusercontent.com/43137324/146784768-629e72de-387f-491f-b343-35fad882b787.png)

Делал давно-давно, чтобы в первую очередь попрактиковаться в верстке, да и вообще не факт, что знал про наборы)

**Comment by Everrest1** [comment]
Видимо старый код

![image](https://user-images.githubusercontent.com/43137324/147272440-c95dccfc-9a01-45e0-8e7c-3c0e67914f99.png)
![image](https://user-images.githubusercontent.com/43137324/147272456-9f7b080e-e348-498d-a330-e7da2c6f17a6.png)
![image](https://user-images.githubusercontent.com/43137324/147272623-96515418-6f3e-4ccf-98e1-6b670b3be3a7.png)
