### ISSUE TITLE
Взаимосвязанность блоков

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#46]
Если кратко, то её не должно быть. [п.4.4](https://github.com/fullstack-development/front-end-best-practices/tree/master/CSS#4.4)

`Самодостаточность говорит о том, что каждый компонент должен внутри себя содержать все необходимое — всю верстку, все стили и все js-скрипты.
`
Чтобы блок был действительно универсальным и максимально переиспользуемым он не должен знать, где он может быть использован, мы и сами этого не знаем) 
А тут блок выглядит, как кусок, вырванный из другого блока

![image](https://user-images.githubusercontent.com/43137324/147763297-c1231e00-f2cb-4c8c-a2aa-17f3804565ae.png)

**Comment by Everrest1** [comment]
Ещё мы не можем использовать внутреннюю структуру других блоков, использовать селекторы по классам напрямую и т.д. Все взаимодействия должны производиться используя заранее подготовленный интерфейс, например, здесь это должны быть публичные методы инстанса js-класса данного блока

![image](https://user-images.githubusercontent.com/43137324/147764054-4b8add81-5b47-42f1-96d1-d7e228236395.png)

**Comment by ArtemDmitrenko** [comment]
Make input component more independent in this commit 21d520fa83c1fe8011921daec8a54f10491dcee3

**Comment by ArtemDmitrenko** [comment]
> Ещё мы не можем использовать внутреннюю структуру других блоков, использовать селекторы по классам напрямую и т.д. Все взаимодействия должны производиться используя заранее подготовленный интерфейс, например, здесь это должны быть публичные методы инстанса js-класса данного блока
> 
> ![image](https://user-images.githubusercontent.com/43137324/147764054-4b8add81-5b47-42f1-96d1-d7e228236395.png)

Здесь я вроде бы ушел от использования внутренней структуры другого блока (input), но на 100% не уверен, что сделал это правильно, посмотри пож

**Comment by Everrest1** [comment]
Осталась проблема использования селекторов для получения внутренних элементов других блоков.
Тут нарушается инкапсуляция блока, такое код делает очень неочевидным поиск ошибок при изменении внутренней структуры блока input. Т.к. мы рассчитываем, что если dom-элементы используются в js, то в рамках текущего блока. А так, представляешь сколько может занять времени поиск среди всех остальных блоков, где этот элемент был найден в querySelector?

![image](https://user-images.githubusercontent.com/43137324/148409491-32acfd5b-9ae1-47a9-bcaf-2fd656a79c2d.png)

**Comment by Everrest1** [comment]
Тоже самое касается и стилей, они все применяются глобально, и чтобы потом не искать по всем файлам, где же было переопределено неработающее свойство, нужно помещать элементы текущего блока в "контейнеры". И ни в коем случае не переопределять стили других блоков

![image](https://user-images.githubusercontent.com/43137324/148410634-387aea3c-4ddf-46ac-9bf6-3f069fd90855.png)
![image](https://user-images.githubusercontent.com/43137324/148410673-982c7bda-324e-42b1-8f20-6e5fa430c6d5.png)
![image](https://user-images.githubusercontent.com/43137324/148410705-78414898-314a-4796-aa58-2f4123f0139d.png)
![image](https://user-images.githubusercontent.com/43137324/148410735-d685ef39-638e-463b-9bb8-e46059bc4313.png)

**Comment by Everrest1** [comment]
Тут осталось

![image](https://user-images.githubusercontent.com/43137324/148971785-ac19e6ca-79d8-4a46-81d1-220067550094.png)

**Comment by Everrest1** [comment]
Этот класс что делает?

![image](https://user-images.githubusercontent.com/43137324/149356021-2e689376-3c04-49d1-a9f0-9439f510b3f8.png)

**Comment by Everrest1** [comment]
header и другие блоки, которые не используются другими блоками могут проинициализировать все свои инстансы самостоятельно. Примерно, как у тебя это сделано в файлах main.js, только по коллекции querySelectAll пройтись forEach

![image](https://user-images.githubusercontent.com/43137324/149797204-bc4ab054-f4cc-475e-b51a-0d4ac8d9e383.png)

В папке ui-kit код давно не обновлялся

![image](https://user-images.githubusercontent.com/43137324/149797567-f96fc020-faf3-4943-a657-a4266e4c0189.png)

**Comment by ArtemDmitrenko** [comment]
> header и другие блоки, которые не используются другими блоками могут проинициализировать все свои инстансы самостоятельно. Примерно, как у тебя это сделано в файлах main.js, только по коллекции querySelectAll пройтись forEach
> 
> ![image](https://user-images.githubusercontent.com/43137324/149797204-bc4ab054-f4cc-475e-b51a-0d4ac8d9e383.png)
> 
> В папке ui-kit код давно не обновлялся
> 
> ![image](https://user-images.githubusercontent.com/43137324/149797567-f96fc020-faf3-4943-a657-a4266e4c0189.png)

Тоесть в случае с хэдером я просто создаю инстанс хэдера:
```
new Header();
```
а в самом js хэдэре уже нахожу элемент header на странице и тд:
```
this.header = document.querySelector("header");
...
```
Тогда не понимаю как инициализировать такие блоки, если их несколько на странице?

**Comment by Everrest1** [comment]
> Тоесть в случае с хэдером я просто создаю инстанс хэдера

Не совсем, тут можно в самом блоке header добавить файл main.js, который будет инициализировать все header'ы, которые найдёт на странице. Если их инстанс не нужен где-то ещё

> Тогда не понимаю как инициализировать такие блоки, если их несколько на странице?

querySelectorAll вернёт все блоки по указанному селектору, по ним можно пройтись forEach и проинициализировать

**Comment by ArtemDmitrenko** [comment]
Пару вопросов по поводу самостоятельной инициализации самих себя:
1. Допустим у меня в проекте блок "карта поиска номеров" не входит ни в какой блок, следовательно, я её переделал  (сделал так, чтобы она сама себя инициализировала). Но в дальнейшем, например, возникла необходимость применить данный блок, но уже в составе другого блока, внутри которого используется инстанс карты поиска номеров. Соответственно, чтобы это сделать мне потребуется вносить какие-то изменения в блок карты поиска номеров, что не есть хорошо. В то время если оставить как было у меня (не самостоятельная инициализация, а по месту, где требуется), то мы бы избежали эту проблему...
2. Я в целом не очень пока понимаю для чего это. Ты написал, чтобы все блоки, которые не используются другими блоками, инициализировались самостоятельно. Но помимо этого, у меня множество блоков "А", которые используется блоками "Б", но инстанс блоков "А" не используется блоком "Б". Ну тоесть они независимы. И в таком случае теоретически можно ведь тоже такие блоки типа "А" инициализировать самостоятельно. Этого не стоит делать? Так как блок "Б" может измениться со временем или по какой-то другой причине?

**Comment by Everrest1** [comment]
1. Ты можешь и оставить как есть, я посоветовал, чтобы немного разгрузить код от дублирующихся инициализаций. Только, чтобы оставить старый вариант, тебе нужно исправить нарушение инкапсуляции блока которого ты инициализируешь
2. Можно, js может выполнять какую-то узкую задачу, которая не виляет ни на что кроме самого блока и не принимает никаких значений из вне. Тогда его можно инициализировать самостоятельно, ведь блок и так является самостоятельной единицей.


Не нужно под инициализацию заводить ещё один класс, достаточно поместить querySelectorAll и пройтись циклом. А импорты можно настроить автоматическими, тогда и проблема с ручными импортами css решиться

![image](https://user-images.githubusercontent.com/43137324/150480539-975ae93c-c353-4140-8e19-ffc60839af5b.png)
