### ISSUE TITLE
Диаграмма

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#49]
> 5. Диаграмма на странице room-details не должна быть просто картинкой. В параметрах нужно передать список значении и построить круговую диаграмму на их основе. [ссылка](https://coda.io/@metalamp/education/-5)

![image](https://user-images.githubusercontent.com/43137324/149357343-94cdcdee-ff2f-4fa7-aaff-d1d9f0c2d433.png)

**Comment by ArtemDmitrenko** [comment]
Так и есть вроде, в параметрах передаются значения, потом они попадают в дата атрибуты и по ним строится диаграмма (логика в js)

> > 5. Диаграмма на странице room-details не должна быть просто картинкой. В параметрах нужно передать список значении и построить круговую диаграмму на их основе. [ссылка](https://coda.io/@metalamp/education/-5)
> 
> ![image](https://user-images.githubusercontent.com/43137324/149357343-94cdcdee-ff2f-4fa7-aaff-d1d9f0c2d433.png)

Так и есть, в параметрах передаются значения, потом они попадают в дата атрибуты и по ним строится диаграмма (логика в js)

**Comment by Everrest1** [comment]
Почему var то?)) Проблема таких динамических data- атрибутов в том, что не очень понятно что туда передаётся и здесь, и в js, + в блок можно передать всё что угодно и при опечатках, опять же, сложно будет понять почему что-то не работает. Ну и цикл for in тоже не очень хорошая практика. Поэтому я бы предложил указать всё-же явно какие параметры записываются в атрибуты. Ну или dataArray записывать в один атрибут целиком "как есть". 
В js же предпочтительнее использовать методы массивов и иммутабельность

![image](https://user-images.githubusercontent.com/43137324/149800123-aa065788-7143-4f5a-9696-0d2996101b49.png)

**Comment by Everrest1** [comment]
В массиве для градиентов здесь смысла нет, потому что всегда используются только 0 и 1 значения, поэтому лучше вместо него передавать объект со свойствами from to

![image](https://user-images.githubusercontent.com/43137324/149801477-ff46a074-bf37-4a05-8ffc-10356e55542a.png)

**Comment by ArtemDmitrenko** [comment]
> 

1. по поводу var у меня почему-то ошибку кидало при сборке, сейчас поменял все ок)
2. Ты пишешь, что при динамических дата-атрибутах непонятно что именно туда попадает и лучше указывать явно какие параметры записываются в дата-атрибуты. Я не понимаю как это сделать, если у нас наименование параметров может быть каким угодно (вместо 'good', 'bad'... что-то другое) и плюс их количество не ограничено, тоесть нужно в любом случая проходить циклом и динамически их формировать.
3. По поводу предложения полностью передавать dataArray в один атрибут я не понял как это решит проблему п. 2 (поможет больше понять что именно передается в атрибуты)??
4. С опечатками я наверно не до конца понимаю, что имеется в виду. Я сейчас не вижу проблему, так как если допустить опечатку и в параметрах вместо `name: good` набрать `name: god`, то на правильность отображения это не повлияет никак. Поясни пож что ты имеешь в виду)

**Comment by Everrest1** [comment]
2. Да, это я не доглядел
Основной гол у меня здесь был в том, что дата атрибуты можно передать вообще любые и у тебя код забирает их все, в том числе не валидное 
![image](https://user-images.githubusercontent.com/43137324/150077769-52d2d9e2-920b-4090-8787-20e808436aa2.png)
3. Использование одного атрибута привязывает нас к атрибуту с конкретным именем, в конечный набор данных в js не попадёт что-то лишнее
4. Да, я на что-то другое подумал

**Comment by Everrest1** [comment]
Для чего model делать объектом ключ-значение, если потом он итерируется циклами?

![image](https://user-images.githubusercontent.com/43137324/150822593-64011253-1a62-4e20-a32f-376a43748e73.png)

**Comment by Everrest1** [comment]
Теперь вместо forEach можно использовать map и сразу присвоить model массив, а вместо мутации obj возвращать объект литералом

![image](https://user-images.githubusercontent.com/43137324/151157012-86d3ebc0-4f84-4a35-ba4b-03975c33597e.png)

reduce можно было оставить)

![image](https://user-images.githubusercontent.com/43137324/151157202-4ee54820-ea9f-4f63-80d0-5e76630fb610.png)

**Comment by Everrest1** [comment]
Пропустил
 
> reduce можно было оставить)
> 
> ![image](https://user-images.githubusercontent.com/43137324/151157202-4ee54820-ea9f-4f63-80d0-5e76630fb610.png)

**Comment by ArtemDmitrenko** [comment]
> Пропустил
> 
> > reduce можно было оставить)
> > ![image](https://user-images.githubusercontent.com/43137324/151157202-4ee54820-ea9f-4f63-80d0-5e76630fb610.png)

Reduce намеренно не сделал, так как показалось, что он больше не нужен. Сейчас ведь model не объект как раньше, а массив с объектами {[...], [...],...}. reduce к массиву вроде как тоже не использовать никак.
