### ISSUE TITLE
Неточности вёрстки

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#54]
Ширина календаря должна соответствовать ширине инпута
При нажатии на стрелочку календарь не выпадает

![image](https://user-images.githubusercontent.com/43137324/150823174-6f633b1b-e77a-451e-b3a9-85f340465c8e.png)

При клике на "применить" ничего не происходит
Соответственно введённое значение при закрытии селекта не сохраняется

![image](https://user-images.githubusercontent.com/43137324/150823741-d0f06ea5-05c7-4b8b-a5f8-66ba719e8185.png)

Думаю это плохая идея оставлять поле совсем пустым)

![image](https://user-images.githubusercontent.com/43137324/150824121-eed06ce5-e007-4143-9520-5d8a243da07c.png)

На кликабельных элементах желательно ограничивать выделение

![image](https://user-images.githubusercontent.com/43137324/150824699-30eb7567-c372-4e58-bf0b-87a350edd1db.png)

Надо обработать кейс, если лайков будет больше

![image](https://user-images.githubusercontent.com/43137324/150825064-50dba41b-f848-4700-b07b-bfbb0bf017d5.png)

Это немного странно, что в инпуте указано 3 гостя, но на самом деле значения там нет

![image](https://user-images.githubusercontent.com/43137324/150825238-3f946b62-79e2-4dc8-bbe0-25fb684a0f18.png)

**Comment by Everrest1** [comment]
После скрытия dropdown значения сохраняются, но поле сбрасывается 

![71b0095b-a4a9-4f58-b87a-fe2afa7a85aa](https://user-images.githubusercontent.com/43137324/151377972-9574fa87-b761-43ac-af8b-d1b9a8ac0fb6.gif)

**Comment by ArtemDmitrenko** [comment]
> После скрытия dropdown значения сохраняются, но поле сбрасывается
> 
> ![71b0095b-a4a9-4f58-b87a-fe2afa7a85aa](https://user-images.githubusercontent.com/43137324/151377972-9574fa87-b761-43ac-af8b-d1b9a8ac0fb6.gif)

Обсудили, решили оставить как есть
