### ISSUE TITLE
Адаптивность

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#57]
На мобилках стрелочки у dropdown скрываются, хотя лучше бы оставить
Календарь съехал

![image](https://user-images.githubusercontent.com/43137324/151378905-5ada8bde-06ad-4d52-bca9-4c4b6b6f2c9d.png)

Отступ нужно сделать поменьше

![image](https://user-images.githubusercontent.com/43137324/151379121-9b796ada-7965-40d5-b2ca-b098f7509763.png)

На 576 пропадает счётчик отзывов

![image](https://user-images.githubusercontent.com/43137324/151379689-2c370ed9-7ba5-4ae3-ae4c-9db5b50834eb.png)

**Comment by ArtemDmitrenko** [comment]
> На мобилках стрелочки у dropdown скрываются, хотя лучше бы оставить Календарь съехал
> 
> ![image](https://user-images.githubusercontent.com/43137324/151378905-5ada8bde-06ad-4d52-bca9-4c4b6b6f2c9d.png)
> 
> Отступ нужно сделать поменьше
> 
> ![image](https://user-images.githubusercontent.com/43137324/151379121-9b796ada-7965-40d5-b2ca-b098f7509763.png)
> 
> На 576 пропадает счётчик отзывов
> 
> ![image](https://user-images.githubusercontent.com/43137324/151379689-2c370ed9-7ba5-4ae3-ae4c-9db5b50834eb.png)

Стрелочки оставить можно, но они тогда буду накладываться на плейсхолдер инпута

**Comment by ArtemDmitrenko** [comment]
Попробовал по максимуму уместить, но все равно на 320px наползают стрелки

**Comment by Everrest1** [comment]
> Попробовал по максимуму уместить, но все равно на 320px наползают стрелки

Так ведь можно сократить отступы от рамок

**Comment by Everrest1** [comment]
Пропала стрелочка

![image](https://user-images.githubusercontent.com/43137324/152148914-a9e62428-0b1f-458c-ad8d-bb44a8327ef5.png)

Не, я имел ввиду эти отступы) Сейчас всё слиплось)

![image](https://user-images.githubusercontent.com/43137324/152149193-40ed7c31-56a2-4fe2-8b60-251d595c2dad.png)

Стрелочка вылезла за пределы календаря

![image](https://user-images.githubusercontent.com/43137324/152149366-32f69ff3-49ef-44b3-8611-bea4cb19b182.png)
