### ISSUE TITLE
Фиксированная ширина и высота

### ISSUE THREAD

**Issue by Everrest1** [ArtemDmitrenko/FSD_task2#60]
Нужно пройтись по проекту и поправить там, где нет необходимости жестко фиксировать ширину и высоту

[п.1.12](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#1.12)
[п.2.5](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.5)

![image](https://user-images.githubusercontent.com/43137324/152376012-3a48ae0b-ddfd-40de-9f0b-b9c4aea916a0.png)

**Comment by Everrest1** [comment]
Оставлю здесь. На остальных страницах тоже нужно уменьшить отступы, чтобы всё умещалось

![image](https://user-images.githubusercontent.com/43137324/153621203-ca091e12-2173-4c02-8d87-cc512f998769.png)

Тут отступы нужно добавить от краёв экрана

![image](https://user-images.githubusercontent.com/43137324/153621258-ec1297e8-bab6-46f6-9bf4-ffda90f88606.png)

А тут добавить отступы от хедера и футера

![image](https://user-images.githubusercontent.com/43137324/153621371-1a32981b-3fa5-4a4e-95d6-7f29af66e803.png)

**Comment by Everrest1** [comment]
Теперь тут карточка залазит на футер

![image](https://user-images.githubusercontent.com/43137324/153895785-b8aafcbc-60e8-4cae-aab3-89db6c4b5179.png)

Поправь ещё инпуты календаря

![image](https://user-images.githubusercontent.com/43137324/153896624-807652d1-2983-4f77-addb-559079b36b42.png)

**Comment by ArtemDmitrenko** [comment]
это исправил еще в прошлый раз, просто забыл gh-pages обновить. Сейчас все ок
